{% set version = "0.1.8" %}
{% set posix = 'm2-' if win else '' %}

package:
  name: r-tcplfit2
  version: {{ version|replace("-", "_") }}

source:
  url:
    - {{ cran_mirror }}/src/contrib/tcplfit2_{{ version }}.tar.gz
    - {{ cran_mirror }}/src/contrib/Archive/tcplfit2/tcplfit2_{{ version }}.tar.gz
  sha256: f0a5496929f3e096ea4659a82c3f98315e9ceb8f83ffec79c9a552beb313bd89

build:
  number: 0
  noarch: generic
  rpaths:
    - lib/R/lib/
    - lib/

requirements:
  build:
    - {{ posix }}zip               # [win]
    - cross-r-base {{ r_base }}    # [build_platform != target_platform]
  host:
    - r-base
    - r-rcolorbrewer
    - r-ggplot2
    - r-numderiv
    - r-reshape2
    - r-stringr
  run:
    - r-base
    - r-rcolorbrewer
    - r-ggplot2
    - r-numderiv
    - r-reshape2
    - r-stringr

test:
  commands:
    - $R -e "library('tcplfit2')"           # [not win]
    - "\"%R%\" -e \"library('tcplfit2')\""  # [win]

about:
  home: https://CRAN.R-project.org/package=tcplfit2
  license: MIT
  summary: Performs the basic concentration response curve fitting used in the 'tcpl' package. It is a substitute for the original tcplFit() function (and sub-functions) and allows a wider variety of concentration-response models. All of the models included in the 'BMDExpress' package are now part of this package, and the
    output includes a calculation of the bmd (Benchmark Dose or concentration) value.
  license_family: MIT
  license_file:
    - {{ environ["PREFIX"] }}/lib/R/share/licenses/MIT
    - LICENSE

extra:
  recipe-maintainers:
    - conda-forge/r
